const words = [
    "algoritmus",
    "programozás",
    "adatbázis",
    "számítógép",
    "program",
    "szoftver",
    "hardver",
    "rendszer",
    "szerver",
    "hálózat",
    "internet",
    "protokoll",
    "weboldal",
    "fejlesztés",
    "kódolás",
    "debuggolás",
    "felhőszolgáltatás",
    "mobilalkalmazás",
    "mesterséges intelligencia",
    "big data",
    "blokklánc",
    "szimuláció",
    "adattárház",
    "szövegszerkesztő",
    "operációs rendszer",
    "felhasználói felület",
    "grafikus felhasználói felület",
    "tárolás",
    "adatkezelés",
    "biztonság",
    "titkosítás",
    "jelszóvédelem",
    "tűzfal",
    "vírusvédelem",
    "hackelés",
    "phishing",
    "szoftverfrissítés",
    "hardverfrissítés",
    "periféria",
    "billentyűzet",
    "egér",
    "monitor",
    "nyomtató",
    "processzor",
    "memória",
    "merevlemez",
    "flash meghajtó",
    "BIOS",
    "feladat",
    "folyamat",
    "szál",
    "szinkronizáció",
    "aszinkron",
    "szálbiztonság",
    "szemafór",
    "kritikus szakasz",
    "blokkoló hívás",
    "interrupt",
    "szálak közötti kommunikáció",
    "memóriakezelés",
    "párhuzamos programozás",
    "szerializáció",
    "deszerializáció",
    "szerveroldali",
    "kliensoldali",
    "IP cím",
    "router",
    "switch",
    "hub",
    "firewall",
    "gateway",
    "modem",
    "Wi-Fi",
    "Ethernet",
    "megosztott hálózat",
    "vezetékes hálózat",
    "vezeték nélküli hálózat",
    "topológia",
    "csomópont",
    "csomóponti hálózat",
    "csillagtopológia",
    "busztopológia",
    "gyűrűtopológia",
    "hibatűrés",
    "teljesítmény",
    "skálázhatóság",
    "felhasználói élmény",
    "ergonómia",
    "interfész",
    "mobilszámítógép",
    "tabletgép",
    "laptop",
    "notebook",
    "szerverpark",
    "virtualizáció"
]